"""empty message

Revision ID: b0e4ed6642d7
Revises: b1b9afcafd1a
Create Date: 2025-06-11 19:44:14.381011

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b0e4ed6642d7"
down_revision = "b1b9afcafd1a"
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sys_dict_data",
        sa.Column("id", sa.BigInteger(), nullable=False, comment="主键"),
        sa.Column("sort", sa.Integer(), nullable=True, comment="字典排序"),
        sa.Column(
            "label", sa.String(length=64), nullable=True, comment="字典标签"
        ),
        sa.Column(
            "value", sa.String(length=64), nullable=True, comment="字典键值"
        ),
        sa.Column(
            "type", sa.String(length=64), nullable=True, comment="字典类型"
        ),
        sa.Column(
            "echo_style",
            sa.String(length=64),
            nullable=True,
            comment="回显样式",
        ),
        sa.Column(
            "ext_class", sa.String(length=64), nullable=True, comment="扩展样式"
        ),
        sa.Column(
            "is_default",
            sa.Integer(),
            nullable=True,
            comment="是否默认(1是 0否)",
        ),
        sa.Column(
            "status", sa.Integer(), nullable=True, comment="状态(1正常 0停用)"
        ),
        sa.Column(
            "comment", sa.String(length=255), nullable=True, comment="备注"
        ),
        sa.Column(
            "create_time", sa.DateTime(), nullable=True, comment="创建时间"
        ),
        sa.Column(
            "update_time", sa.DateTime(), nullable=True, comment="更新时间"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="字典数据表",
    )
    op.create_table(
        "sys_dict_type",
        sa.Column("id", sa.BigInteger(), nullable=False, comment="主键"),
        sa.Column(
            "name", sa.String(length=64), nullable=True, comment="字典名称"
        ),
        sa.Column(
            "type", sa.String(length=64), nullable=True, comment="字典类型"
        ),
        sa.Column(
            "status", sa.Integer(), nullable=True, comment="状态(1正常 0停用)"
        ),
        sa.Column(
            "comment", sa.String(length=255), nullable=True, comment="备注"
        ),
        sa.Column(
            "create_time", sa.DateTime(), nullable=True, comment="创建时间"
        ),
        sa.Column(
            "update_time", sa.DateTime(), nullable=True, comment="更新时间"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type", name="dict_type"),
        comment="字典类型表",
    )
    op.create_table(
        "sys_menu",
        sa.Column("id", sa.BigInteger(), nullable=False, comment="主键"),
        sa.Column("name", sa.String(length=50), nullable=False, comment="名称"),
        sa.Column("icon", sa.String(length=100), nullable=True, comment="图标"),
        sa.Column(
            "permission",
            sa.String(length=100),
            nullable=True,
            comment="权限标识",
        ),
        sa.Column("sort", sa.Integer(), nullable=True, comment="排序"),
        sa.Column(
            "path", sa.String(length=200), nullable=True, comment="路由地址"
        ),
        sa.Column(
            "component",
            sa.String(length=255),
            nullable=True,
            comment="组件路径",
        ),
        sa.Column(
            "type",
            sa.Integer(),
            nullable=True,
            comment="类型（1目录 2菜单 3按钮）",
        ),
        sa.Column(
            "cacheable",
            sa.Integer(),
            nullable=True,
            comment="是否缓存（1缓存 0不缓存）",
        ),
        sa.Column(
            "visible",
            sa.Integer(),
            nullable=True,
            comment="是否显示（1显示 0隐藏）",
        ),
        sa.Column("parent_id", sa.Integer(), nullable=True, comment="父ID"),
        sa.Column(
            "status", sa.Integer(), nullable=True, comment="状态（1正常 0停用）"
        ),
        sa.Column(
            "create_time", sa.DateTime(), nullable=True, comment="创建时间"
        ),
        sa.Column(
            "update_time", sa.DateTime(), nullable=True, comment="更新时间"
        ),
        sa.Column(
            "comment", sa.String(length=500), nullable=True, comment="备注信息"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="系统菜单表",
    )
    op.create_index("idx_parent_id", "sys_menu", ["parent_id"], unique=False)
    op.create_table(
        "sys_role",
        sa.Column("id", sa.BigInteger(), nullable=False, comment="角色ID"),
        sa.Column(
            "name", sa.String(length=30), nullable=False, comment="角色名称"
        ),
        sa.Column(
            "code",
            sa.String(length=100),
            nullable=False,
            comment="角色权限字符串",
        ),
        sa.Column("sort", sa.Integer(), nullable=False, comment="显示顺序"),
        sa.Column(
            "data_scope",
            sa.Integer(),
            nullable=True,
            comment="数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）",
        ),
        sa.Column(
            "data_scope_dept_ids",
            sa.String(length=500),
            nullable=True,
            comment="数据范围(指定部门数组)",
        ),
        sa.Column(
            "status",
            sa.Integer(),
            nullable=False,
            comment="角色状态（0正常 1停用）",
        ),
        sa.Column(
            "comment", sa.String(length=500), nullable=True, comment="备注"
        ),
        sa.Column(
            "create_time", sa.DateTime(), nullable=True, comment="创建时间"
        ),
        sa.Column(
            "update_time", sa.DateTime(), nullable=True, comment="更新时间"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="角色信息表",
    )
    op.create_table(
        "sys_role_menu",
        sa.Column("id", sa.BigInteger(), nullable=False, comment="自增编号"),
        sa.Column("role_id", sa.Integer(), nullable=False, comment="角色ID"),
        sa.Column("menu_id", sa.Integer(), nullable=False, comment="菜单ID"),
        sa.Column(
            "create_time", sa.DateTime(), nullable=True, comment="创建时间"
        ),
        sa.Column(
            "update_time", sa.DateTime(), nullable=True, comment="更新时间"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="角色和菜单关联表",
    )
    op.create_table(
        "sys_user_role",
        sa.Column("id", sa.BigInteger(), nullable=False, comment="自增编号"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="用户ID"),
        sa.Column("role_id", sa.Integer(), nullable=False, comment="角色ID"),
        sa.Column(
            "create_time", sa.DateTime(), nullable=True, comment="创建时间"
        ),
        sa.Column(
            "update_time", sa.DateTime(), nullable=True, comment="更新时间"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="用户和角色关联表",
    )
    op.execute("""
        INSERT INTO `sys_menu` VALUES (1, '系统管理', 'system-manage', NULL, 2, '/system', NULL, 1, NULL, 1, 0, NULL, NULL, NULL, NULL);
    """)
    op.execute("""
        INSERT INTO `sys_menu` VALUES (5, '工具箱', 'tool', NULL, 8, '/tool', NULL, 1, NULL, 1, 0, NULL, NULL, NULL, NULL);
    """)
    op.execute("""
        INSERT INTO `sys_menu` VALUES (12, '用户管理', NULL, NULL, 1, '/system/user', NULL, 2, NULL, 1, 1, NULL, NULL, NULL, NULL);
    """)
    op.execute("""
        INSERT INTO `sys_menu` VALUES (14, '菜单管理', NULL, NULL, 3, '/system/menu', NULL, 2, NULL, 1, 1, NULL, NULL, NULL, NULL);
    """)
    op.execute("""
        INSERT INTO `sys_menu` VALUES (15, '角色管理', NULL, NULL, 4, '/system/role', NULL, 2, NULL, 1, 1, NULL, NULL, NULL, NULL);
    """)
    op.execute("""
        INSERT INTO `sys_menu` VALUES (17, '代码生成', 'code', NULL, 2, '/tool/code', NULL, 2, NULL, 1, 5, NULL, NULL, NULL, NULL);
    """)
    op.execute("""
        INSERT INTO `sys_menu` VALUES (19, '系统监控', 'monitor', NULL, 10, '/monitor', NULL, 1, NULL, 1, 0, NULL, NULL, NULL, NULL);
    """)
    op.execute("""
        INSERT INTO `sys_menu` VALUES (20, '异常页面', 'bug', NULL, 11, '/exception', NULL, 1, NULL, 0, 0, NULL, NULL, NULL, NULL);
    """)
    op.execute("""
        INSERT INTO `sys_menu` VALUES (24, '首页', 'home', NULL, 1, '/home', NULL, 1, NULL, 1, 0, NULL, NULL, NULL, NULL);
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sys_user_role")
    op.drop_table("sys_role_menu")
    op.drop_table("sys_role")
    op.drop_index("idx_parent_id", table_name="sys_menu")
    op.drop_table("sys_menu")
    op.drop_table("sys_dict_type")
    op.drop_table("sys_dict_data")
    # ### end Alembic commands ###
