"""empty message

Revision ID: 1f2573cd228f
Revises:
Create Date: 2025-05-20 22:12:39.612144

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1f2573cd228f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sys_user",
        sa.Column("id", sa.BigInteger(), nullable=False, comment="主键"),
        sa.Column("username", sa.String(length=32), nullable=True, comment="用户名"),
        sa.Column("password", sa.String(length=64), nullable=True, comment="密码"),
        sa.Column("nickname", sa.String(length=32), nullable=True, comment="昵称"),
        sa.Column("avatar", sa.String(length=64), nullable=True, comment="头像"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        comment="用户信息表",
    )
    op.create_index(op.f("ix_sys_user_username"), "sys_user", ["username"], unique=True)

    # 添加自定义的 INSERT 语句
    op.execute("""
        INSERT INTO "sys_user" ("id", "username", "password", "nickname", "create_time", "update_time")
        VALUES (72607707435008, 'admin', '$2b$12$CxVv3BQY7AnXXACbQ2ZXMO4XzjqGSvDG0oSh4e.k4LgFdaAQ4oZGW', '管理员', '2025-05-20 22:04:31.328280', '2025-05-20 22:04:31.328280')
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sys_user_username"), table_name="sys_user")
    op.drop_table("sys_user")
    # ### end Alembic commands ###
